### ISSUE TITLE
Jako opiekun chcę dodawać nagrody do listy nagród podopiecznego

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_full_stack#17]
check if BE is ready

**Comment by adrian13508** [comment]
Backend is done for now, but should be rethinked / redesigned as mentoned in task https://github.com/zetonteam/zeton_django/issues/86

**Comment by martinafm** [comment]
task done https://github.com/zetonteam/zeton_react/pull/82
